# instance configuration for template 'metric'
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: requestcount
  namespace: istio-system
spec:
  value: "1"
  dimensions:
    source_cluster: source.labels["cluster"] | "unknown"
    source_service: source.labels["service"] | "unknown"
    source_version: source.labels["version"] | "unknown"
    destination_cluster: destination.labels["cluster"] | "unknown"
    destination_service: destination.labels["service"] | "unknown"
    destination_version: destination.labels["version"] | "unknown"
    response_code: response.code | 200
  monitored_resource_type: '"UNSPECIFIED"'
---
# instance configuration for template 'logentry'
apiVersion: "config.istio.io/v1alpha2"
kind: logentry
metadata:
 name: accesslog
 namespace: istio-system
spec:
 severity: '"Default"'
 timestamp: request.time
 variables:
  sourceCluster: source.labels["cluster"] | "unknown"
  sourceService: source.labels["service"] | "unknown"
  sourceIp: source.ip | ip("0.0.0.0")
  destinationCluster: destination.labels["cluster"] | "unknown"
  destinationService: destination.labels["service"] | "unknown"
  destinationIp: destination.ip | ip("0.0.0.0")
  sourceUser: source.user | ""
  method: request.method | ""
  url: request.path | ""
  protocol: request.scheme | "http"
  responseCode: response.code | 0
  responseSize: response.size | 0
  requestSize: request.size | 0
  latency: response.duration | "0ms"
 monitored_resource_type: '"UNSPECIFIED"'
---
# handler configuration for adapter
apiVersion: "config.istio.io/v1alpha2"
kind: cloudwatch
metadata:
 name: handler
 namespace: istio-system
spec:
 namespace: "cloudwatch-istio"
 metricInfo:
  requestcount.metric.istio-system:
   unit: Count
 logGroupName: "TestLogGroup"
 logStreamName: "TestLogStream"
 logs:
  accesslog.logentry.istio-system:
    payloadTemplate: '{{or (.sourceIp) "-"}} - {{or (.sourceUser) "-"}} [{{or (.timestamp.Format "2006-01-02T15:04:05Z07:00") "-"}}] "{{or (.method) "-"}} {{or (.url) "-"}} {{or (.protocol) "-"}}" {{or (.responseCode) "-"}} {{or (.responseSize) "-"}}'
---
# rule to dispatch to your handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
 name: mysamplerule
 namespace: istio-system
spec:
 match: "true"
 actions:
 - handler: handler.cloudwatch
   instances:
   - requestcount.metric
   - accesslog.logentry
